[background-color="#01303a"]
== Model Your Project with Gradle and Kotlin: Your Project as Software Components

//* Projects (`org.gradle.api.Project`)
//** Models isolated parts of your software
//** To be tested, published, etc. independently
//** Model architecture
//*** by layer (`model`, `services`, `app`) - plugins apply on project level
//*** by domain (`user-model`, `account-model`)
//* Tasks (`org.gradle.api.Task`)
//** Models configurable work that is performed during a build
//* Configurations (`org.gradle.api.artifacts.Configuration`)
//** Models dependencies between projects/modules and the artifacts they produce/provide

=== Your Project as a Software Component

[plantuml, components1, png, width=300, height=0%]
....
!include <cloudinsight/cog>
scale 300 width

skinparam monochrome true

["<size:62><&question-mark></size>"]
....

=== Don't be afraid of Gradle - it's just Kotlin

`build.gradle.kts`
[source,kotlin]
----
// empty file
----

`settings.gradle.kts`
[source,kotlin]
----
rootProject.name = "kotlin-everywhere"
----

=== Don't be afraid of Gradle - it's just Kotlin

`build.gradle.kts`
[source,kotlin]
----
tasks.register("t1") {
    inputs.dir("...")
    ouptuts.file("...")
    doLast {
        ...
    }
}
----

`settings.gradle.kts`
[source,kotlin]
----
rootProject.name = "kotlin-everywhere"
----

=== Don't be afraid of Gradle - it's just Kotlin

`build.gradle.kts`
[source,kotlin]
----
tasks.register("t1") {
    inputs.dir("...")
    ouptuts.file("...")
    doLast {
        // do some work
    }
}
----

`settings.gradle.kts`
[source,kotlin]
----
rootProject.name = "kotlin-everywhere"
----

//=== Gradle Build Lifecycle
//
//`build.gradle.kts`
//[source,kotlin]
//----
//println("(1) build.gradle.kts - build configuration - 1")
//
//plugins     { println("(2) build.gradle.kts - plugins configuration") }
//buildscript { println("(3) build.gradle.kts - buildscript block") }
//
//tasks.register("t1") {
//    doLast { println("(4) Running $name - only action") }
//    println("(5) build.gradle.kts - $name task config")
//}
//tasks.register("t2") {
//    doLast  { println("(6) Running $name - second action") }
//    doFirst { println("(7) Running $name - first action") }
//    println("(8) build.gradle.kts - $name task config")
//}
//println("(9) build.gradle.kts - build configuration - 2")
//----
//
//`settings.gradle.kts`
//[source,kotlin]
//----
//rootProject.name = "kotlin-everywhere"
//println("(10) settings.gradle.kts - evaluating settings")
//----
//
//=== Gradle Build Lifecycle
//
//`gradlew t1 t2`
//[source,kotlin]
//----
//(10) settings.gradle.kts - evaluating settings
//
//> Configure project :
//(2) build.gradle.kts - plugins configuration
//(3) build.gradle.kts - buildscript block
//(1) build.gradle.kts - build configuration - 1
//(9) build.gradle.kts - build configuration - 2
//(5) build.gradle.kts - t1 task config
//(8) build.gradle.kts - t2 task config
//
//> Task :t1
//(4) Running t1 - only action
//
//> Task :t2
//(7) Running t2 - first action
//(6) Running t2 - second action
//
//BUILD SUCCESSFUL
//----

=== Don't be afraid of Gradle - it's just Kotlin

`buildSrc/src/main/kotlin/MyProject.kt`
[source,kotlin]
----
object MyProject {
    fun org.gradle.api.Project.configureMyProject() {
        tasks.register("t1") {
            inputs.dir("...")
            ouptuts.file("...")
            doLast {
                // do some work
            }
        }
    }
}
----

`build.gradle.kts`
[source,kotlin]
----
configureMyProject()
----

You define a model of your software project through a Java/Kotlin API

Entry point: `org.gradle.api.Project`

=== Your Project as a Software Component

[plantuml, components1, png, width=300, height=0%]
....
!include <cloudinsight/cog>
scale 300 width

skinparam monochrome true
skinparam defaultTextAlignment center

["<$cog> <$cog>\n   <$cog>"]
....

You define a model of your software project through a Java/Kotlin API

Entry point: `org.gradle.api.Project`

=== Your Project as a Software Component

[source,kotlin]
----
fun org.gradle.api.Project.configureMyProject() {
    println("Tasks: ${tasks.size}")
    plugins.apply("java")
    println("Tasks: ${tasks.size} (Java plugin added)")
    plugins.apply("org.jetbrains.kotlin.jvm")
    println("Tasks: ${tasks.size} (Kotlin plugin added)")
    plugins.apply("com.android.application")
    println("Tasks: ${tasks.size} (Android plugin added)")
}
----

[source,kotlin]
----
> Configure project :
Tasks: 16
Tasks: 31 (Java plugin added)
Tasks: 36 (Kotlin plugin added)
Tasks: 49 (Android plugin added)
----

You define a model of your software project through a Java/Kotlin API

Entry point: `org.gradle.api.Project`

=== Your Project as a Software Component

[plantuml, components2, png, width=300, height=0%]
....
!include <cloudinsight/cog>
!include <cloudinsight/java>
scale 300 width

skinparam monochrome true
skinparam defaultTextAlignment center

["<$cog> <$java>\n<$cog>"]
....

You define a model of your software project through a Java/Kotlin API

Entry point: `org.gradle.api.Project`


=== Your Project as multiple Software Components

[plantuml, components3, png, width=500, height=0%]
....
!include <cloudinsight/cog>
!include <cloudinsight/java>
scale 500 width

skinparam monochrome true
skinparam defaultTextAlignment center

[:user-data\n\n]
[:account-data\n\n]
[:services\n\n]
[:desktop-app\n\n]
[:android-app\n\n]
....

`settings.gradle.kts`
[source,kotlin]
----
include("user-data", "account-data", "services", "desktop-app", "android-app")
----

=== Your Project as multiple Software Components

[plantuml, components5, png, width=500, height=0%]
....
!include <cloudinsight/cog>
!include <cloudinsight/java>
scale 500 width

skinparam monochrome true
skinparam defaultTextAlignment center

[:user-data\n\n(<&cog> Java)]
[:account-data\n\n(<&cog> Java)]
[:services\n\n(<&cog> Kotlin)]
[:desktop-app\n\n(<&cog> Kotlin)]
[:android-app\n\n(<&cog> Android)]
....

[source,kotlin]
----
project(":user-data").plugins.apply("java")
project(":account-data").plugins.apply("java")
project(":services").plugins.apply("org.jetbrains.kotlin.jvm")
project(":desktop-app").plugins.apply("org.jetbrains.kotlin.jvm")
project(":android-app").plugins.apply("org.jetbrains.kotlin.android")
project(":android-app").plugins.apply("com.android.application")
----

=== Your Project as multiple Software Components

[plantuml, components4, png, width=650, height=0%]
....
!include <cloudinsight/cog>
!include <cloudinsight/java>
scale 650 width

skinparam monochrome true
skinparam defaultTextAlignment center

[:user-data\n\n<&folder> data/user-data/...]
[:account-data\n\n<&folder> data/account-data/...]
[:services\n\n<&folder> services/services/...]
[:desktop-app\n\n<&folder> apps/desktop-app/...]
[:android-app\n\n<&folder> apps/android-app/...]
....

`settings.gradle.kts`
[source,kotlin]
----
include("user-data", "account-data", "services", "desktop-app", "android-app")
rootProject.children.forEach {
    val base = when(it.name) {
        "user-data"    -> "data"
        "account-data" -> "data"
        "services"     -> "services"
        else           -> "apps"
    }
    it.projectDir = file("$base/${it.name}")
}
----