[background-color="#01303a"]
== Model Your Project with Gradle and Kotlin: Variant-Aware Dependency Management

=== Dependency Management

[plantuml, components2-1, png, width=600, height=0%]
....
scale 600 width
skinparam monochrome true
skinparam defaultTextAlignment left
left to right direction

[:user-data\n\n] as UD
[:account-data\n\n] as AD
[:services\n\n] as S
[:desktop-app\n\n] as DAPP
[:android-app\n\n] as AAPP

UD<--S
AD<--S
S<--DAPP
S<--AAPP
....

=== Variant-Aware Dependency Management

[plantuml, components2-1, png, width=600, height=0%]
....
scale 600 width
skinparam monochrome true
skinparam defaultTextAlignment left
left to right direction

[:user-data\n\n] as UD
[:account-data\n\n] as AD
[:services\n\n] as S
[:desktop-app\n\n] as DAPP
[:android-app\n\n] as AAPP

UD<--S
AD<--S
S<--DAPP
S<--AAPP
....

Entry point: `org.gradle.api.artifacts.Configuration` (API for 3 concepts)

* *Provide*: define sets of artifacts I produce for other projects
* *Consume*: define sets of dependencies to projects and modules
* *Resolve*: tool to collect artifacts from dependencies (e.g. all _jars_)


=== Variant-Aware Dependency Management
[plantuml, components2-2-1, png, width=400, height=0%]
....
scale 400 width
skinparam monochrome true
skinparam defaultTextAlignment left
left to right direction

[:services\n\n<&box> everythingYouNeedToRunMe] as S
[:desktop-app\n\n] as DAPP

S<--DAPP
....


*Provide*: define sets of artifacts I produce for other projects (:services)
[source,kotlin]
----
val everythingYouNeedToRunMe by configurations.creating {
    isCanBeResolved = false; isCanBeConsumed = true
}
----

=== Variant-Aware Dependency Management
[plantuml, components2-2-2, png, width=600, height=0%]
....
scale 600 width
skinparam monochrome true
skinparam defaultTextAlignment left
left to right direction

[:services\n\n<&box> everythingYouNeedToRunMe] as S
[:desktop-app\n\n] as DAPP

S<--DAPP : otherComponentsINeedToRun
....


*Provide*: define sets of artifacts I produce for other projects (:services)

[source,kotlin]
----
val everythingYouNeedToRunMe by configurations.creating {
    isCanBeResolved = false; isCanBeConsumed = true
    extendsFrom(otherComponentsINeedToRun)
}
----

*Consume*: define sets of dependencies to projects and modules (:desktop-app)

[source,kotlin]
----
val otherComponentsINeedToRun by configurations.creating {
    isCanBeResolved = false; isCanBeConsumed = false
}
dependencies {
    otherComponentsINeedToRun(project(":services"))
}
----

=== Variant-Aware Dependency Management
[plantuml, components2-2-3, png, width=600, height=0%]
....
scale 600 width
skinparam monochrome true
skinparam defaultTextAlignment left
left to right direction

[:services\n\n<&box> everythingYouNeedToRunMe] as S
[:desktop-app\n\n] as DAPP

S<--DAPP : otherComponentsINeedToRun
....

*Resolve*: tool to collect artifacts from dependencies (e.g. all _jars_)
[source,kotlin]
----
val pathToAllFiles by configurations.creating {
    isCanBeResolved = true; isCanBeConsumed = true
    extendsFrom(otherComponentsINeedToRun)
}
tasks.register("allFiles") {
    doLast {
        println(configurations["pathToAllFiles"].incoming
            .artifacts.artifactFiles.map { it.name })
    }
}
----

`gradlew desktop-app:allFiles`
[source,kotlin]
----
> Task :desktop-app:allFiles
[services.jar, services-sources.jar]
----

=== Consume other Projects and Modules

[plantuml, components2-4, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant] as UD
[os:slf4j-api:1.7.13\n\n] as LOG
[cc:disruptor:1.2.15\n\n] as DIS
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`desktop-app/build.gradle.kts`
[source,kotlin]
----
dependencies {
    implementation(project(":services"))
}
----

`services/build.gradle.kts`
[source,kotlin]
----
dependencies {
    api(project(":user-data"))
    implementation("com.conversantmedia:disruptor:1.2.15")
}
----

=== Resolve with Variant Selection
[plantuml, components2-5, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as UD #moccasin
[os:slf4j-api:1.7.13\n\n] as LOG
[cc:disruptor:1.2.15\n\n] as DIS
[:services\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`gradlew desktop-app:dependencies --configuration compileClasspath`
[source,kotlin]
----
compileClasspath
\--- project :services
     \--- project :user-data
----

=== Resolve with Variant Selection
[plantuml, components2-6, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>] as UD #moccasin
[os:slf4j-api:1.7.13\n\n] as LOG #moccasin
[cc:disruptor:1.2.15\n\n] as DIS #moccasin
[:services\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`gradlew desktop-app:dependencies --configuration compileClasspath`
[source,kotlin]
----
compileClasspath
\--- project :services
     \--- project :user-data
----

`gradlew desktop-app:dependencies --configuration runtimeClasspath`
[source,kotlin]
----
runtimeClasspath
\--- project :services
     +--- project :user-data
     \--- com.conversantmedia:disruptor:1.2.15
          \--- org.slf4j:slf4j-api:1.7.13
----

=== Resolve with Variant Selection
[plantuml, components2-7, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant] as UD
[os:slf4j-api:1.7.13\n\n] as LOG
[cc:disruptor:1.2.15\n\n] as DIS
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`gradlew services:outgoingVariants`
[source,xml]
----
Variant api-variant
--------------------------------------------------
Attributes
- org.gradle.jvm.version         = 11
- org.gradle.libraryelements     = classes
- org.gradle.usage               = java-api
----


`desktop-app/build.gradle.kts`
[source,kotlin]
----
configurations["compileClasspath"].attributes {
    attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_RUNTIME))
}
----

=== Resolve with Variant Selection
[plantuml, components2-8, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>] as UD #moccasin
[os:slf4j-api:1.7.13\n\n] as LOG #moccasin
[cc:disruptor:1.2.15\n\n] as DIS #moccasin
[:services\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`desktop-app/build.gradle.kts`
[source,kotlin]
----
configurations["compileClasspath"].attributes {
    attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_RUNTIME))
}
----

`gradlew desktop-app:dependencies --configuration compileClasspath`
[source,kotlin]
----
compileClasspath
\--- project :services
     +--- project :user-data
     \--- com.conversantmedia:disruptor:1.2.15
          \--- org.slf4j:slf4j-api:1.7.13
----

=== Resolve with Variant Selection
[plantuml, components2-9, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>\n<&box> rt-8-variant] as UD #moccasin
[os:slf4j-api:1.7.13\n\n] as LOG #moccasin
[cc:disruptor:1.2.15\n\n] as DIS #moccasin
[:services\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>\n <&box> rt-8-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....
//
//`desktop-app/build.gradle.kts`
//[source,kotlin]
//----
//tasks.register("jars") {
//    doLast {
//        println(configurations["runtimeClasspath"].incoming
//            .artifacts.artifactFiles.map { it.name })
//    }
//}
//----

`desktop-app/build.gradle.kts`
[source,kotlin]
----
configurations["runtimeClasspath"].attributes {

}
----

`gradlew desktop-app:allFiles`
[source,kotlin]
----
> Task :desktop-app:allFiles
[services.jar, user-data.jar, disruptor-1.2.15.jar,
 slf4j-api-1.7.13.jar]
----

=== Resolve with Variant Selection
[plantuml, components2-10, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<back:orangered><&box> rt-8-variant</back>] as UD #moccasin
[os:slf4j-api:1.7.13\n\n] as LOG #moccasin
[cc:disruptor:1.2.15\n\n] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<back:orangered><&box> rt-8-variant</back>] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`desktop-app/build.gradle.kts`
[source,kotlin]
----
configurations["runtimeClasspath"].attributes {
    attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 8)
}
----

`gradlew desktop-app:allFiles`
[source,kotlin]
----
> Task :desktop-app:allFiles
[services-jdk8.jar, user-data-jdk8.jar,
 disruptor-1.2.15.jar, slf4j-api-1.7.13.jar]
----


=== What about Published Modules?
[plantuml, components2-12, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as UD
[os:slf4j-api:1.7.13\n\n] as LOG #moccasin
[cc:disruptor:1.2.15\n\n] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as S
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

* For projects: Gradle has the full model in memory
* For modules: Gradle needs to build the model from metadata

=== POM Module Metadata
[plantuml, components2-13, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as UD
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as S
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`com/conversantmedia/disruptor/1.2.15/disruptor-1.2.15.pom`
[source,xml]
----
<groupId>com.conversantmedia</groupId>
<artifactId>disruptor</artifactId>
<packaging>jar</packaging>
<version>1.2.15</version>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.13</version>
    <scope>compile</scope>
</dependency>
----

=== POM Module Metadata
[plantuml, components2-14, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as UD
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as S
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`com/conversantmedia/disruptor/1.2.15/*.jar`

[source,sh]
----
disruptor-1.2.15-jdk10.jar      2018-12-20 14:41    134319
disruptor-1.2.15-jdk8.jar       2018-12-20 14:41    134482
disruptor-1.2.15.jar            2018-12-20 14:41    134482
----

=== Gradle Module Metadata (GMM)
[plantuml, components2-15, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as UD
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<&box> rt-8-variant] as S
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`disruptor-1.2.15.module`
[source,json]
----
"component": { "group": "com.conversantmedia", "module": "disruptor", "version": "1.2.15" },
"variants": [
  { "name": "runtimeElements",
    "attributes": { "org.gradle.jvm.version": 11, "org.gradle.usage": "java-runtime" },
    "dependencies": [{ "group": "org.slf4j", "module": "slf4j-api", "version": { "requires": "1.7.13" }}],
    "files": [{ "name": "conversantmedia-1.2.15.jar", "url": "conversantmedia-1.2.15.jar" }] },
  { "name": "jdk8RuntimeElements",
    "attributes": { "org.gradle.jvm.version": 8, "org.gradle.usage": "java-runtime" },
    "dependencies": [{ "group": "org.slf4j", "module": "slf4j-api", "version": { "requires": "1.7.13" }}],
    "files": [{ "name": "conversantmedia-1.2.15-jdk8.jar", "url": "conversantmedia-1.2.15-jdk8.jar" }]
  },
----

=== Variant Selection on Projects and Modules
[plantuml, components2-15, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<&box> api-variant\n<&box> rt-variant\n<back:orangered><&box> rt-8-variant</back>] as UD #moccasin
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<back:orangered><&box> rt-variant</back>] as LOG #moccasin
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant\n<back:orangered><&box> rt-8-variant</back>] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant\n<back:orangered><&box> rt-8-variant</back>] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP #moccasin
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
DIS<--S : implementation
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

`desktop-app/build.gradle.kts`
[source,kotlin]
----
configurations["runtimeClasspath"].attributes {
    attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 8)
}
----

`gradlew desktop-app:allFiles`
[source,kotlin]
----
> Task :desktop-app:allFiles
[services-jdk8.jar, user-data-jdk8.jar,
 disruptor-1.2.15-jdk8.jar, slf4j-api-1.7.13.jar]
----
