[background-color="#01303a"]
== Model Your Project with Gradle and Kotlin: Features building on Variant-Aware Dependency Management

// all these features are also published!

=== Handle conflicting Implementations

[plantuml, components3-2-1, png, width=600, height=0%]
....
scale 600 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[l4j:log4j:1.2.12\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as L4J #moccasin
[os:log4j-over-slf4j:1.7.13\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as OVER #moccasin
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
[v:velocity:1.5\n\n<&box> api-variant\n<&box> rt-variant] as VEL
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S

L4J <-- VEL : api
VEL <-- S : implementation
OVER <-- S : implementation
DIS<--S : implementation
LOG<--DIS : api
....

// `serivices/build.gradle.kts`

[source,kotlin]
----
dependencies {
    implementation("velocity:velocity:1.5")
    implementation("org.slf4j:log4j-over-slf4j:1.7.10")
}
----

* *Capabilities*: Provided by variants, each can be provided only once
* *Attributes*: Define which implementation of a capability fits best

=== Handle conflicting Implementations

[plantuml, components3-2-2, png, width=800, height=0%]
....
scale 800 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[l4j:log4j:1.2.12\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as L4J #moccasin
[os:log4j-over-slf4j:1.7.13\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as OVER #moccasin
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
[v:velocity:1.5\n\n<&box> api-variant\n<&box> rt-variant] as VEL
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S
rectangle "Capability\nl4j:log4j:1.2.12" as CAP #pink

L4J <-- VEL : api
VEL <-- S : implementation
OVER <-- S : implementation
DIS<--S : implementation
LOG<--DIS : api

CAP <.. L4J
CAP <.. OVER
....

// `serivices/build.gradle.kts`

[source,kotlin]
----
dependencies {
    implementation("velocity:velocity:1.5")
    implementation("org.slf4j:log4j-over-slf4j:1.7.10")
}
----

* *Capabilities*: Provided by variants, each can be provided only once
* *Attributes*: Define which implementation of a capability fits best

=== Handle conflicting Implementations

[plantuml, components3-2-3, png, width=800, height=0%]
....
scale 800 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[l4j:log4j:1.2.12\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as L4J #moccasin
[os:log4j-over-slf4j:1.7.13\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as OVER #moccasin
[os:slf4j-api:1.7.13\n\n<&box> api-variant\n<&box> rt-variant] as LOG
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
[v:velocity:1.5\n\n<&box> api-variant\n<&box> rt-variant] as VEL
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S
rectangle "Capability\nl4j:log4j:1.2.12" as CAP #pink

L4J <-- VEL : api
VEL <-- S : implementation
OVER <-- S : implementation
DIS<--S : implementation
LOG<--DIS : api

CAP <.. L4J
CAP <.. OVER
....

// `serivices/build.gradle.kts`

[source,kotlin]
----
dependencies {
    implementation("velocity:velocity:1.5")
    implementation("org.slf4j:log4j-over-slf4j:1.7.10")
}
----

[source,kotlin]
----
Cannot select module with conflict on capability 'log4j:log4j:1.2.12'
also provided by [org.slf4j:log4j-over-slf4j:1.7.13(api-variant)]
----

=== Handle conflicting Implementations

// dependencies {
//   components.all(LoggingCapability::class.java)
//}

[source,kotlin]
----
class LoggingCapability : ComponentMetadataRule {
  val loggingModules = setOf("log4j", "log4j-over-slf4j")
  override fun execute(ctx: ComponentMetadataContext) = ctx.details.run {
    if (loggingModules.contains(id.name)) {
      allVariants {
        withCapabilities { addCapability("log4j", "log4j", id.version) }
      }
    }
  }
}
----

* *Component Metadata Rules*: Add missing metadata

----
configurations.all {
  resolutionStrategy.capabilitiesResolution.withCapability("log4j:log4j") {
    select(candidates.find { it.module == "log4j-over-slf4j" })
    because("use slf4j in place of log4j")
  }
}
----

* *Capability Resolution Strategy*: Decide what fits in your context

=== Test Fixtures

`user-data/src/main/java/com/acme/User.kt`
[source,kotlin]
----
data class User(val firstName: String, val lastName: String)
----

`user-data/src/testFixtures/java/com/acme/Simpsons.kt`
[source,kotlin]
----
object Simpsons {
    val HOMER  = User("Homer", "Simpson")
    val MARGE  = User("Majorie", "Simpson")
    val BART   = User("Bartholomew", "Simpson")
    val LISA   = User("Elisabeth Marie", "Simpson")
    val MAGGIE = User("Margaret Eve", "Simpson")
    val FAMILY = setOf(HOMER, MARGE, BART, LISA, MAGGIE)
}
----

`user-data/build.gradle.kts`
[source,kotlin]
----
plugins {
    `java-library`
    `java-test-fixtures` // new plugin since Gradle 5.6
    `maven-publish`      // you can publish test fixtures with GMM!
}
----

=== Test Fixtures
[plantuml, components3-1, png, width=900, height=0%]
....
scale 900 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[:user-data\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant\n<back:orangered><&box> fixtures-varian</back>] as UD #moccasin
[os:slf4j-api:1.7.13\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant] as LOG #moccasin
[cc:disruptor:1.2.15\n\n<back:orangered><&box> api-variant</back>\n<&box> rt-variant\n<back:orangered><&box> fixtures-varian</back>] as DIS #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP

UD<--S : api
UD<--S : testImpl
DIS<--S : implementation
DIS<--S : testImpl
LOG<--DIS : api
S<--DAPP : implementation
S<--AAPP : implementation
....

// `services/build.gradle.kts`
[source,kotlin]
----
dependencies {
    api(project(":user-data"))
    implementation("com.conversantmedia:disruptor:1.2.15")
    testImplementation(testFixtures(project(":user-data")))
    testImplementation(testFixtures("com.conversantmedia:disruptor:1.2.15"))
}
----

=== Versions and Version Conflicts

[plantuml, components3-3, png, width=600, height=0%]
....
scale 600 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[os:slf4j-api:<back:lightgreen>1.7.13</back>\n\n<&box> api-variant\n<&box> rt-variant] as LOG #moccasin
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
[os:slf4j-api:<back:red>1.6.6</back>\n\n<&box> api-variant\n<&box> rt-variant] as LOG6 #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S

LOG6 <-- S : api
DIS <--  S : implementation
LOG <--  DIS : api
....

* For projects: Gradle always uses/builds the working copy
* For modules: Gradle needs to choose a version
** Gradle considers *all* version constraints in the dependency graph

[source,kotlin]
----
dependencies {
    implementation("com.conversantmedia:disruptor:1.2.15")
    api("org.slf4j:slf4j-api") {
        version { requires("1.6.6") }
    }
}
----

=== Versions and Version Conflicts

[plantuml, components3-4, png, width=600, height=0%]
....
scale 600 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[os:slf4j-api:<back:lightgreen>1.7.13</back>\n\n<&box> api-variant\n<&box> rt-variant] as LOG #moccasin
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
rectangle "os:slf4j-api:<back:red>1.6.6</back>" as LOG6 #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S

LOG6 <.. S : api
DIS <--  S : implementation
LOG <--  DIS : api
....

[source,kotlin]
----
dependencies {
    implementation("com.conversantmedia:disruptor:1.2.15")
    constraints {
        api("org.slf4j:slf4j-api") {
            version {
                requires("1.6.6")
            }
        }
    }
}
----

=== Versions and Version Conflicts

[plantuml, components3-5, png, width=600, height=0%]
....
scale 600 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}

[os:slf4j-api:<back:red>1.7.13</back>\n\n<&box> api-variant\n<&box> rt-variant] as LOG #moccasin
[cc:disruptor:1.2.15\n\n<&box> api-variant\n<&box> rt-variant] as DIS
rectangle "os:slf4j-api:<back:lightgreen>1.6.6</back>" as LOG6 #moccasin
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S

LOG6 <.. S : api
DIS <--  S : implementation
LOG <--  DIS : api
....

[source,kotlin]
----
dependencies {
    implementation("com.conversantmedia:disruptor:1.2.15")
    constraints {
        api("org.slf4j:slf4j-api") {
            version {
                requires("1.6.6")
                forSubgraph()
            }
        }
    }
}
----

=== Platforms for Managing Dependency Versions
[plantuml, components3-6, png, width=680, height=0%]
....
scale 680 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}


[:user-data\n\n<&box> api-variant\n<&box> rt-variant] as UD
[:account-data\n\n<&box> api-variant\n<&box> rt-variant] as AD
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP
[:my-platform] as P #moccasin

UD<--S : api
AD<--S : api
S<--DAPP : implementation
S<--AAPP : implementation
P<--UD
P<--AD
P<--S
P<-DAPP
P<-AAPP
....

[source,kotlin]
----
plugins { `java-platform` }
dependencies {
    constraints {
        api("com.conversantmedia:disruptor:1.2.15")
        api("org.slf4j:slf4j-api:1.6.6") { version { forSubgraph() } }
    }
}
----

=== Platforms for Managing Dependency Versions
[plantuml, components3-7, png, width=680, height=0%]
....
scale 680 width
skinparam defaultTextAlignment left
left to right direction
skinparam component {
    ArrowColor black
    BorderColor black
    BackgroundColor white
}


[:user-data\n\n<&box> api-variant\n<&box> rt-variant] as UD
[:account-data\n\n<&box> api-variant\n<&box> rt-variant] as AD
[:services\n\n<&box> api-variant\n<&box> rt-variant] as S #moccasin
[:desktop-app\n\n<&box> rt-variant] as DAPP
[:android-app\n\n<&box> rt-variant] as AAPP
[:my-platform] as P

UD<--S : api
AD<--S : api
S<--DAPP : implementation
S<--AAPP : implementation
P<--UD
P<--AD
P<--S
P<-DAPP
P<-AAPP
....

[source,kotlin]
----
dependencies {
    api(platform(project(":my-platform")))
    implementation("com.conversantmedia:disruptor")
}
----

